import fs from 'node:fs';
import path from 'node:path';

const ZONES = ['raw', 'drafts', 'ready'];

function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i > 0) out[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return out;
}

// files: { relPath: content } — injectable for tests
export function buildIndex(files) {
  const rows = [];
  for (const [rel, content] of Object.entries(files)) {
    const m = rel.match(/^specs\/(raw|drafts|ready)\/([^/]+)\/([^/]+)\/README\.md$/);
    if (!m) continue;
    const [, zone, product, feature] = m;
    const fm = parseFrontmatter(content);
    rows.push({ product, feature, zone, flow: fm.flow || '', created: fm.created || '' });
  }
  const byProduct = {};
  for (const r of rows) (byProduct[r.product] ||= []).push(r);

  let out = '<!-- AUTO-GENERATED by .claude/spec-tools/regen-index.mjs — do not edit by hand. -->\n';
  out += '# Spec Index\n';
  for (const product of Object.keys(byProduct).sort()) {
    out += `\n## ${product}\n\n| feature | zone | flow | created |\n|---|---|---|---|\n`;
    for (const r of byProduct[product].sort((a, b) => a.feature.localeCompare(b.feature))) {
      out += `| ${r.feature} | ${r.zone} | ${r.flow} | ${r.created} |\n`;
    }
  }
  return out;
}

function readTree(root) {
  const files = {};
  for (const zone of ZONES) {
    const base = path.join(root, 'specs', zone);
    if (!fs.existsSync(base)) continue;
    for (const product of fs.readdirSync(base)) {
      const pdir = path.join(base, product);
      if (!fs.statSync(pdir).isDirectory()) continue;
      for (const feature of fs.readdirSync(pdir)) {
        const readme = path.join(pdir, feature, 'README.md');
        if (fs.existsSync(readme)) {
          files[`specs/${zone}/${product}/${feature}/README.md`] = fs.readFileSync(readme, 'utf8');
        }
      }
    }
  }
  return files;
}

// CLI: regenerate specs/INDEX.md in place
if (import.meta.url === `file://${process.argv[1]}`) {
  const root = process.cwd();
  fs.writeFileSync(path.join(root, 'specs', 'INDEX.md'), buildIndex(readTree(root)));
  console.log('specs/INDEX.md regenerated');
}
